language: go

go:
  - 1.9
  - tip

go_import_path: github.com/turbonomic/turbo-api

before_install:
  - go get -v github.com/mattn/goveralls

matrix:
  allow_failures:
    - go: tip

script:
  - make fmtcheck
  - $HOME/gopath/bin/goveralls -v -race -service=travis-ci -ignore="example/*"

